### ISSUE TITLE
Put more info on how to use

### ISSUE THREAD

**Issue by suryansh00123** [BridgeSenseMC/Dank-Memer-Grinder#2]
Write more instructions on installation and working.

**Comment by BridgeSenseMC** [comment]
> Write more instructions on installation and working.

I will, still currently working on finishing up some bugs and making executables with pyinstaller, I'll make a release when everything is done

**Comment by Snowwy513** [comment]
suryansh i have a better grinder than this it had regular updates just text me on Snowwy#3260
