### ISSUE TITLE
Update When? ;_;

### ISSUE THREAD

**Issue by suryansh00123** [BridgeSenseMC/Dank-Memer-Grinder#23]
..

**Comment by 1010saf** [comment]
prob pretty soon, as i noticed that the version.txt updated to '1.2.0' 6 days ago(at the time iam posting this comment)...
but it may take a lot of time to come out, maybe never idk for sure

**Comment by 1010saf** [comment]
@suryansh00123 oh ic....
iam just a random kid that uses autofarms lol

**Comment by BridgeSenseDev** [comment]
> I have been waiting for more than 1 month. Other competitors have started emerging with new updates for dank memer selfbot and i dont want to stop using this autobot, thats why i have been persistent towards the developer to update it ASAP. 
> BTW, who are you?? @1010saf 

I have been busy with exams for the last month, there will be frequent updates in about 2 weeks and I will fix the commands and captcha
